version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "khoren93"
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "khoren93"
  - package-ecosystem: "pub"
    directory: "/example"
    schedule:
      interval: "weekly"
    reviewers:
      - "khoren93"
