name: flutter_zxing
description: A barcode scanner and generator natively in Flutter with Dart FFI based on ZXing.
version: 0.1.2
repository: https://github.com/khoren93/flutter_zxing

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  camera: ^0.9.4
  ffi: ^1.1.2
  flutter:
    sdk: flutter
  flutter_beep: ^1.0.0
  image: ^3.1.3

dev_dependencies:
  ffigen: ^4.1.3 # dart run ffigen
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.markosyan.flutter_zxing
        pluginClass: FlutterZxingPlugin
      ios:
        pluginClass: FlutterZxingPlugin

ffigen:
  name: GeneratedBindings
  description: Bindings to `native_verokit.h`.
  output: "lib/generated_bindings.dart"
  headers:
    entry-points:
      - "ios/Classes/src/native_zxing.h"

# flutter pub publish --dry-run