name: zxscanner
description: A barcode scanner application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.5
  flex_color_scheme: ^5.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.10
  flutter_mobx: ^2.0.5
  flutter_zxing:
    path: ../
  font_awesome_flutter: ^10.1.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  image: ^3.2.0
  image_picker: ^0.8.5
  intl: ^0.17.0
  mobx: ^2.0.7
  path_provider: ^2.0.10
  share_plus: ^4.0.6
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.2

flutter_intl:
  main_locale: en_US
  enabled: true

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator:
  mobx_codegen:


flutter:
  uses-material-design: true
